#!/usr/bin/env python3
"""
orchestrator.py — Top-level driver for the 3-stage meta-loop.

Stage 1: BIG model defines strategy -> produces a DAG of tasks, each tagged
         with a target_model (registry key) + required_capability.
Stage 2: SMALL models execute -> StageGateScheduler drains affinity groups,
         workers run/iterate the simulation harnesses (Track 3 tools).
Stage 3: BIG model judges -> reads results, decides pass/fail, proposes edits.

This file is the wiring. The actual "big model" call is a pluggable function
(default: a dry-run stub that prints the strategy) so the same code path works
whether the big model is the 70B RPC pipeline or Qwythos-9B-v2.
"""
from __future__ import annotations

import asyncio
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))  # for mcp.cluster_config

from task_graph import Task, make_task
from scheduler import StageGateScheduler
from trace import Trace
from worker_state import NodeView
from judge import judge as _judge_results, judge_to_json as _judge_to_json

# Output locations for the self-documenting artifacts.
TRACE_JSON = os.path.join(HERE, "last_run_trace.json")
TRACE_DOT = os.path.join(HERE, "last_run_trace.dot")


async def _default_dispatch(node: NodeView, task: Task) -> None:
    """PRODUCTION dispatch: run the method harness ON THE NODE via SSH.

    Compute stays on-node; only the JSON result dict crosses the wire (the
    project's 'compute over latency' invariant). The task's input_data is
    'METHOD: <instruction>' — we parse the method name and run it on the node
    assigned by the scheduler. The FP16 instruction payload (if present) is
    attached to the task before dispatch so the agent receives BOTH the text
    instruction and its float16 embedding companion vector."""
    # Attach the FP16 embedding companion if not already present.
    if not task.fp16_instruction_b64:
        try:
            from mcp.embed_client import embed_text_sync
            emb = embed_text_sync(task.input_data)
            if emb is not None:
                from task_graph import attach_fp16_instruction
                attach_fp16_instruction(task, emb)
        except Exception as e:  # noqa: BLE001
            task.log("FP16_PAYLOAD", f"skipped (embedding tier offline): {e}")

    # Parse the method name from input_data ("METHOD: ...").
    method = task.input_data.split(":", 1)[0].strip().lower()
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    import mcp.cluster_config as _cfg
    import subprocess
    cmd = f"cd /home/jetson/methods && python3 harness.py {method} --json"
    task.log("DISPATCH", f"exec {method} on {node.ip} via SSH (compute-on-node)")
    proc = await asyncio.to_thread(
        subprocess.run,
        ["ssh"] + _cfg.SSH_OPTS + [f"{_cfg.SSH_USER}@{node.ip}", cmd],
        capture_output=True, text=True, timeout=300)
    if proc.returncode == 0:
        task.result = proc.stdout.strip()
        task.log("RESULT", f"{method} OK on {node.ip} ({len(task.result)} bytes)")
    else:
        task.result = json.dumps({"_method": method, "error": proc.stderr.strip()[:200]})
        task.log("ERROR", f"{method} failed on {node.ip}: {proc.stderr.strip()[:120]}")


async def stage1_define_strategy(big_model_fn) -> List[Task]:
    """Stage 1: ask the big model to decompose the problem into a task DAG."""
    # big_model_fn returns a list of (capability, model, data, deps) tuples.
    plan = await big_model_fn()
    tasks = [make_task(cap, model, data, deps=deps)
             for (cap, model, data, deps) in plan]
    for t in tasks:
        t.log("STRATEGY", "Generated by big model in Stage 1.")
    return tasks


async def stage3_judge(tasks: List[Task], big_model_fn) -> str:
    """Stage 3: judge Phase-2 results against the theory, critique the math,
    and propose manuscript edits. The deterministic rubric judge runs first
    (audit trail); big_model_fn adds natural-language prose on top."""
    # Collect Phase-2 result dicts (each task.result is a JSON method result
    # carrying a '_method' tag from harness.run).
    results = []
    for t in tasks:
        if not t.result:
            continue
        raw = t.result.strip()
        # Strip any SSH/stdio noise (warnings, prompts) before the first '{'.
        try:
            start = raw.index("{")
            end = raw.rindex("}") + 1
            parsed = json.loads(raw[start:end])
        except (json.JSONDecodeError, TypeError):
            parsed = None
        if isinstance(parsed, dict):
            results.append(parsed)
        else:
            # Non-JSON or non-dict task result (e.g. a reasoning task, or a
            # double-encoded string) — skip for the rubric, but still hand the
            # raw text to the model.
            results.append({"_method": t.task_id, "_raw": t.result})

    verdict = _judge_results(results)
    # Optional large-model prose layer (production: 70B / DeepSeek-R1-32B).
    if big_model_fn is not None:
        try:
            prose = await big_model_fn(json.dumps(verdict, indent=2))
            verdict["manuscript_edits"] = prose
        except Exception:  # noqa: BLE001
            verdict["manuscript_edits"] = "[model layer unavailable]"
    return _judge_to_json(verdict)


async def run_pipeline(plan_fn, judge_fn, dispatch=None, trace_path_json=TRACE_JSON,
                       trace_path_dot=TRACE_DOT) -> Trace:
    """Full 3-stage run. Returns the immutable trace."""
    dispatch = dispatch or _default_dispatch
    trace = Trace()

    # Stage 1
    tasks = await stage1_define_strategy(plan_fn)
    trace.tasks.extend(tasks)

    # Stage 2
    sched = StageGateScheduler(dispatch)
    sched.submit_many(tasks)
    gate = 0
    while any(t.status == "PENDING" for t in tasks):
        await sched.run_gate()
        gate += 1
        allocs = [{"task": t.task_id, "model": t.target_model,
                   "justification": t.strategy_justification}
                  for t in tasks if t.status == "DONE" and
                  not any(g.get("allocations") for g in trace.gates if t.task_id in [a["task"] for a in g["allocations"]])]
        trace.record_gate(gate, allocs)
        if gate > 50:
            break

    # Stage 3
    verdict = await stage3_judge(tasks, judge_fn)
    for t in tasks:
        t.log("STAGE3_VERDICT", verdict[:120])

    trace.to_json(trace_path_json)
    trace.to_dot(trace_path_dot)
    return trace


# Example plan: the 6 Anti-Dark Forest methodologies mapped to small models.
# (Model keys must exist in mcp.cluster_config.MODELS — register them first.)
EXAMPLE_PLAN = [
    ("MATH", "phi-4-mini", "MARL: EROI of kinetic vs assimilation strike.", []),
    ("MATH", "phi-4-mini", "Monte Carlo cosmic ergodicity (10M timelines).", []),
    ("CODE", "qwen3-4b", "Thermodynamic cellular automata (Free Energy Principle).", []),
    ("MATH", "phi-4-mini", "KL-divergence: simulate bio-chaos vs harvest it.", []),
    ("CODE", "qwen3-4b", "Lean system dynamics supply-chain model.", []),
    ("MATH", "gemma-4-e4b", "Epistemic Bayesian game theory (blindness vs transparency).", []),
    ("REASON", "gemma-4-e4b", "Final integration: what could have been done better?",
     ["TASK_MARL", "TASK_MC", "TASK_CA", "TASK_KL", "TASK_LEAN", "TASK_BAYES"]),
]


async def _example_plan_fn():
    # Map the example plan to real task ids for the dependency edge.
    ids = ["TASK_MARL", "TASK_MC", "TASK_CA", "TASK_KL", "TASK_LEAN", "TASK_BAYES"]
    out = []
    for i, (cap, model, data, _deps) in enumerate(EXAMPLE_PLAN):
        deps = [] if i < 6 else ids
        out.append((cap, model, data, deps))
    await asyncio.sleep(0)
    return out


async def _example_judge_fn(summary: str) -> str:
    await asyncio.sleep(0)
    return (f"[dry-run judge] Reviewed {len(summary.splitlines())} task results. "
            f"Thesis holds pending empirical sweep.")


# ---------------------------------------------------------------------------
# PRODUCTION BIG-MODEL PLUG-IN  (DeepSeek-R1-Distill-Qwen-32B on the cluster)
# ---------------------------------------------------------------------------
# Stage 1 + Stage 3 call the 32B sharded across all 11 Jetson nodes. This is
# the whole reason the cluster exists: a single PC cannot hold the 32B, and it
# is the model that generates the strategy DAG and writes the manuscript prose.
def _big_model_32b(prompt: str, n_predict: int = 1024) -> str:
    """Synchronous call to the 32B; wrapped for the async orchestrator."""
    from llm_client import complete, is_available
    if not is_available():
        return "[32B unavailable — is cluster_server.py running the 32B?]"
    return complete(prompt, n_predict=n_predict)


async def stage1_strategy_32b() -> list:
    """Stage 1: the 32B decomposes the Anti-Dark-Forest theory into a task DAG.

    Returns a list of (capability, model, data, deps) tuples, exactly the shape
    stage1_define_strategy expects. The 32B is asked to map the 11 propositions
    to the 11 method harnesses and declare dependencies.
    """
    prompt = (
        "You are the Strategist in a 3-phase research loop testing the "
        "'Biology as Bounded Information' (Anti-Dark-Forest) thesis on an "
        "11-node Jetson cluster. Define Stage 1 strategy: produce a DAG of 11 "
        "tasks, one per simulation method "
        "(marl, montecarlo, thermo_ca, kl_div, lean, bayesian, viability_kernel, "
        "replication_thermo, tiep_lifetime, jevons_throughput, recursive_viability). "
        "Each task: capability=MATH/CODE/REASON, model='small', data=a one-line "
        "instruction naming the method and what it must measure, deps=[] (all "
        "independent — they run in parallel on separate nodes). Reply ONLY with "
        "the 11 tasks, one per line, format: METHOD|CAP|DATA."
    )
    out = _big_model_32b(prompt, n_predict=512)
    await asyncio.sleep(0)  # keep coroutine; real I/O is sync via llm_client
    tasks = []
    for line in out.splitlines():
        line = line.strip()
        if "|" not in line:
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 3:
            continue
        method, cap, data = parts[0], parts[1], parts[2]
        tasks.append((cap, "small", f"{method}: {data}", []))
    # Fallback: if the 32B returned nothing parseable, use the canonical 11.
    if not tasks:
        methods = ["marl", "montecarlo", "thermo_ca", "kl_div", "lean", "bayesian",
                   "viability_kernel", "replication_thermo", "tiep_lifetime",
                   "jevons_throughput", "recursive_viability"]
        tasks = [(("MATH" if m in ("marl", "montecarlo", "kl_div", "bayesian")
                   else "CODE"), "small", f"{m}: execute method harness on node",
                  []) for m in methods]
    return tasks


async def stage3_prose_32b(verdict_json: str) -> str:
    """Stage 3: the 32B reads the deterministic rubric verdict and writes the
    manuscript prose (integration, what could be improved, proposed edits in
    natural language)."""
    prompt = (
        "You are the Judge in a 3-phase research loop. Below is the deterministic "
        "rubric verdict for the 'Biology as Bounded Information' thesis (Phase-3 "
        "JSON: propositions pass/fail, critique findings, blind-spot audit). "
        "Write the manuscript integration section: (1) what the evidence supports, "
        "(2) the two honest failures (P2 heuristic seeding, P6 bi-modal silence) and "
        "how to fix their metrics, (3) concrete next edits. Be precise, no fluff.\n\n"
        f"{verdict_json}"
    )
    await asyncio.sleep(0)  # keep coroutine; real I/O is sync via llm_client
    return _big_model_32b(prompt, n_predict=1500)


if __name__ == "__main__":
    async def _main():
        # Production run: Stage 1 + Stage 3 driven by the 32B on the cluster.
        tr = await run_pipeline(stage1_strategy_32b, stage3_prose_32b)
        print(f"Trace written: {TRACE_JSON}")
        print(f"Graph written: {TRACE_DOT}")
        print(f"Tasks: {len(tr.tasks)}, Gates: {len(tr.gates)}")
    asyncio.run(_main())
