#!/usr/bin/env bash
# Setup script for Jetson Nano worker nodes.
#
# Run this script once on each Jetson Nano after a fresh JetPack install.
# It installs:
#   - Python dependencies (numpy, pycuda, pyyaml)
#   - llama.cpp RPC server binary (compiled from source for aarch64 + CUDA)
#
# Usage:
#   chmod +x scripts/setup_worker.sh
#   ./scripts/setup_worker.sh [--node-id nano-01] [--master-host 192.168.1.1]
#
# JetPack requirement: JetPack 4.6+ (CUDA 10.2+) or JetPack 5.x (CUDA 11.x)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_ID="${NODE_ID:-}"
MASTER_HOST="${MASTER_HOST:-192.168.1.1}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --node-id)     NODE_ID="$2";     shift 2 ;;
        --master-host) MASTER_HOST="$2"; shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

echo "=== Jetson Nano Cluster — Worker Setup ==="
echo "Repo:        $REPO_ROOT"
echo "Node ID:     ${NODE_ID:-<auto-generated>}"
echo "Master host: $MASTER_HOST"
echo

# ---------------------------------------------------------------------------
# 1. System prerequisites
# ---------------------------------------------------------------------------
echo "[1/5] Installing system prerequisites..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    build-essential \
    cmake \
    git \
    python3-pip \
    python3-dev \
    libopenblas-dev \
    libgomp1

# ---------------------------------------------------------------------------
# 2. Python dependencies
# ---------------------------------------------------------------------------
echo "[2/5] Installing Python dependencies..."
pip3 install --upgrade pip
pip3 install -r "$REPO_ROOT/worker/requirements.txt"

# ---------------------------------------------------------------------------
# 3. Build llama.cpp RPC server (aarch64 + CUDA)
# ---------------------------------------------------------------------------
echo "[3/5] Building llama.cpp RPC server..."

LLAMA_DIR="/opt/llama.cpp"
if [[ ! -d "$LLAMA_DIR" ]]; then
    sudo git clone --depth=1 https://github.com/ggerganov/llama.cpp "$LLAMA_DIR"
fi

cd "$LLAMA_DIR"
sudo git pull --ff-only

# Jetson Nano uses the Maxwell GPU (compute capability 5.3).
# This architecture is fixed for all Nano models and is not auto-detected.
CUDA_ARCH="53"
if command -v nvcc &>/dev/null; then
    echo "  CUDA version: $(nvcc --version | grep -oP 'release \K[0-9.]+' | head -1)"
fi

sudo cmake -B build \
    -DGGML_CUDA=ON \
    -DGGML_RPC=ON \
    -DCMAKE_CUDA_ARCHITECTURES="$CUDA_ARCH" \
    -DCMAKE_BUILD_TYPE=Release

sudo cmake --build build --config Release -j"$(nproc)"

# Install the RPC server binary system-wide
sudo install -m 755 build/bin/llama-rpc-server /usr/local/bin/llama-rpc-server

echo "  llama-rpc-server installed at /usr/local/bin/llama-rpc-server"

# ---------------------------------------------------------------------------
# 4. Create systemd service for the worker
# ---------------------------------------------------------------------------
echo "[4/5] Creating systemd service..."

NODE_ID_ARG=""
if [[ -n "$NODE_ID" ]]; then
    NODE_ID_ARG="--node-id $NODE_ID"
fi

sudo tee /etc/systemd/system/jetson-nano-worker.service > /dev/null <<EOF
[Unit]
Description=Jetson Nano Cluster Worker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$REPO_ROOT
Environment="PYTHONPATH=$REPO_ROOT"
ExecStart=/usr/bin/python3 -m worker.worker \\
    --master-host $MASTER_HOST \\
    ${NODE_ID_ARG}
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable jetson-nano-worker.service

echo "  Service created: jetson-nano-worker.service"

# ---------------------------------------------------------------------------
# 5. Verify
# ---------------------------------------------------------------------------
echo "[5/5] Verifying installation..."

if command -v llama-rpc-server &>/dev/null; then
    echo "  llama-rpc-server: OK"
else
    echo "  WARNING: llama-rpc-server not found on PATH"
fi

if python3 -c "import numpy; print('  numpy:', numpy.__version__)"; then
    :
else
    echo "  WARNING: numpy not importable"
fi

echo
echo "=== Worker setup complete ==="
echo "Start the worker service with:"
echo "  sudo systemctl start jetson-nano-worker.service"
echo "Or run directly:"
echo "  python3 -m worker.worker --master-host $MASTER_HOST ${NODE_ID_ARG}"
